name: build

on:
  workflow_dispatch:
    inputs:
      registry:
        description: 'build registry'
        required: true
        type: string
      version:
        description: 'build version'
        required: true
        type: string

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CR_PAT }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./${{ github.event.inputs.registry }}/Dockerfile
          platforms: linux/amd64
          build-args: |
            VERSION=${{ github.event.inputs.version }}
          push: true
          tags: |
            ghcr.io/lintmx/${{ github.event.inputs.registry }}:${{ github.event.inputs.version }}
